# Generated by Django 4.1.4 on 2023-01-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=1600.0)),
                ('image_url', models.URLField()),
                ('author', models.CharField(max_length=32)),
            ],
        ),
    ]
