# Generated by Django 4.1.4 on 2023-01-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
